name: CI - Image Build

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - quayioimage-sr
  pull_request: 
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  parse-list:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.getdirs2scan.outputs.paths }}  # Set the output for this job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main:main  # Ensure main branch is available

      - name: List unique top-level directories of changed files
        id: getdirs2scan
        run: |
          # Show debug results
          unique_paths=$(python3 tools/gitDiffAnalysis.py --exclusions 'tools' '*.md' '.github')
          echo "Unique paths: $unique_paths"
          
          # Write the paths to the environment file for later steps
          echo "paths=$unique_paths" >> $GITHUB_ENV

      - name: Set paths as output
        id: set_output_paths
        run: |
          echo "paths=$unique_paths" >> $GITHUB_ENV

  run-template:
    needs: parse-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJson(needs.parse-list.outputs.paths || '[]') }}  # Use job output as matrix input, fallback to empty array
    steps:
      - name: Debug: Check matrix path
        run: |
          echo "Matrix path: ${{ matrix.path }}"

      - name: Call reusable workflow with matrix value
        uses: ./.github/workflows/quayio-image-template.yml
        with:
          value: ${{ matrix.path }}
