

name: CI - Image Build

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - quayioimage-sr
  pull_request: 
    types: [opened, reopened, synchronize]
    branches: [main]
    
jobs: 
  parse-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: List unique top-level directories of changed files
      id: getdirs2scan
      run: |
        pwd
        ls -l
        unique_paths=$(python3 tools/gitDiffAnalysis.py --exclusions 'tools' '*.md' '.github')
        echo "dirs=$unique_paths" >> $GITHUB_OUTPUT
        echo "list=$(echo ${values[@]} | jq -c -R 'split(" ")')" >> $GITHUB_ENV
        echo $GITHUB_OUTPUT

    outputs:
      list-of-values: ${{ steps.parse.outputs.list }}
            
  call-template:
    needs: parse-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.parse-list.outputs.list-of-values) }}
    steps:
      - name: Call reusable workflow with matrix value
        uses: ./.github/workflows/quayio-image-template.yml
        with:
          value: ${{ matrix.value }}
