name: CI - Image Build

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - quayioimage-sr
  pull_request: 
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  parse-list:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.getdirs2scan.outputs.paths }}  # Output paths for use in the next job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main:main  # Ensure the main branch is available

      - name: List unique top-level directories of changed files
        id: getdirs2scan
        run: |
          # Get changed directories and store them in a variable
          unique_paths=$(python3 tools/gitDiffAnalysis.py --exclusions 'tools' '*.md' '.github')
          echo "Unique paths: $unique_paths"
          
          # Convert the paths to a JSON string (valid for GitHub Actions)
          unique_paths_json=$(echo "$unique_paths" | jq -c '.')
          
          # Save the JSON string to the outputs using the new method
          echo "paths=$unique_paths_json" >> $GITHUB_ENV

      - name: Set output for paths
        id: set_output_paths
        run: |
          # Debugging output to ensure paths are set properly
          echo "paths=$(cat $GITHUB_ENV)"
          echo "::set-output name=paths::$(cat $GITHUB_ENV)"  # Set output for next job

  run-template:
    needs: parse-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJson(needs.parse-list.outputs.paths || '[]') }}  # Use job output for matrix, fallback to empty array
    steps:
      - name: Debug Check matrix path
        run: |
          echo "Matrix path: ${{ matrix.path }}"

      - name: Call reusable workflow with matrix value
        uses: ./.github/workflows/quayio-image-template.yml
        with:
          value: ${{ matrix.path }}
