name: Quay Build & Publish

on:
  push:
    branches:
      - ci/quay
      - main
      - testingmouni

# Service Name can take any of the following values:
#   all - to build all services and push to quay
#   json-lake - to build and push json-lake image
#   debatcher - to build and push debatcher image
#   validator - to build and push validator image
#   redactor - to build and push redactor image
env:
  QUAY_REPOSITORY: "us-cdcgov/cdc-dex"
  SERVICE_NAME: "none"
  JSON_LAKE_CHANGED: FALSE
  DEBATCHER_CHANGED: FALSE
  REDACTOR_CHANGED: FALSE
  VALIDATOR_CHANGED: FALSE

jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Runner @${{ github.actor }}
        run: |
          echo "--------------------------------------------------"
          echo "Workflow was run by: @${{ github.actor }}"
          echo "Service Name: ${{ env.SERVICE_NAME }}"
          echo "--------------------------------------------------"

      - name: Identify Changed Folders
        run: |
          # Check if there are changes in each folder
          if git diff --name-only HEAD~2..HEAD | grep -q -E '\bhl7v2-json-lake\b'; then
            echo "JSON_LAKE_CHANGED=TRUE" >> $GITHUB_ENV
            echo "Json-lake changes detected"
          fi

          if git diff --name-only HEAD~2..HEAD | grep -E '\bhl7v2-debatcher\b'; then
            echo "DEBATCHER_CHANGED=TRUE" >> $GITHUB_ENV
            echo "Debatcher changes detected"
          fi

          if git diff --name-only HEAD~2..HEAD | grep -q -E '\bhl7v2-redactor\b'; then
            echo "REDACTOR_CHANGED=TRUE" >> $GITHUB_ENV
            echo "Redactor changes detected"
          fi

          if git diff --name-only HEAD~2..HEAD | grep -q -E '\bhl7v2-validation\b'; then
            echo "VALIDATOR_CHANGED=TRUE" >> $GITHUB_ENV
            echo "Validator changes detected"
          fi

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      # Build and push Validator
      - name: Build & Push hl7-validator
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'validator' || env.VALIDATOR_CHANGED == 'TRUE'}}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-validation/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:$VERSION ./hl7v2-validation
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:$VERSION

      # Build and push Debatcher
      - name: Build & Push hl7-debatcher
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'debatcher' || env.DEBATCHER_CHANGED == 'TRUE' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-debatcher/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:$VERSION ./hl7v2-debatcher
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:$VERSION

      # Build and push Json-lake
      - name: Build & Push hl7-json-lake
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'json-lake' || env.JSON_LAKE_CHANGED == 'TRUE' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-json-lake/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:$VERSION ./hl7v2-json-lake
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:$VERSION

      # Build and push Redactor
      - name: Build & Push hl7-redactor
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'redactor' || env.REDACTOR_CHANGED == 'TRUE' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-redactor/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION ./hl7v2-redactor
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION
