name: Docker Image Build & Publish

on:
  push:
    branches:
      - quayioimage
  workflow_dispatch:
    inputs:
      service_name:
        type: choice
        description: Service/Image To Build
        options:
          - hl7v2-validation
          - hl7v2-redactor
          - hl7v2-json-lake
          - hl7v2-debatcher
      version_tag:
        description: "Docker Image Version"
        required: true
        type: string

# Specify variable SERVICE_NAME to build and publish specific image to Quay
#   Options are all, json-lake, validator, debatcher, redactor
env:
  QUAY_REPOSITORY: "us-cdcgov/cdc-dex"
  SERVICE_NAME: "hl7v2-debatcher"

jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runner @${{ github.actor }}
        run: |
          echo "--------------------------------------------------"
          echo "Workflow was run by: @${{ github.actor }}"
          echo "Service Name: ${{ env.SERVICE_NAME }}"
          echo "--------------------------------------------------"

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build and push Validator
      - name: Build & Push hl7-validator
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'hl7v2-validation'}}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-validation/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:$VERSION ./hl7v2-validation
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:$VERSION

      # Build and push Debatcher
      - name: Build & Push hl7-debatcher
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'hl7v2-debatcher' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-debatcher/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*.*/\')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:$VERSION ./hl7v2-debatcher
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:$VERSION

      # Build and push Json-lake
      - name: Build & Push hl7-json-lake
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'hl7v2-json-lake' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-json-lake/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:$VERSION ./hl7v2-json-lake
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:$VERSION

      # Build and push Redactor
      - name: Build & Push hl7-redactor
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'hl7v2-redactor' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-redactor/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION ./hl7v2-redactor
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION