name: Quay Build & Publish

on:
  push:
    branches:
      - ci/quay
      - main
  # workflow_dispatch:
  #   inputs:
  #     service_name:
  #       type: choice
  #       description: Service/Image To Build
  #       options:
  #         - validation
  #         - debatcher
  #         - redactor
  #         - lake
  #     version_tag:
  #       description: "Docker Image Version"
  #       required: true
  #       type: string

# Specify variable SERVICE_NAME to build and publish specific image to Quay
#   Options are all, json-lake, validator, debatcher, redactor
env:
  QUAY_REPOSITORY: "us-cdcgov/cdc-dex"
  SERVICE_NAME: "redactor"

jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runner @${{ github.actor }}
        run: |
          echo "--------------------------------------------------"
          echo "Workflow was run by: @${{ github.actor }}"
          echo "Service Name: ${{ env.SERVICE_NAME }}"
          echo "Tag: ${{ env.VERSION_TAG }}"
          echo "--------------------------------------------------"

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Get project version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build and push Validator
      - name: Build & Push hl7-validator
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'validator'}}
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:${{ env.VERSION_TAG }} ./hl7v2-validation
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator:${{ env.VERSION_TAG }}

      # Build and push Debatcher
      - name: Build & Push hl7-debatcher
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'debatcher' }}
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:${{ env.VERSION_TAG }} ./hl7v2-debatcher
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher:${{ env.VERSION_TAG }}

      # Build and push Json-lake
      - name: Build & Push hl7-json-lake
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'json-lake' }}
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:${{ env.VERSION_TAG }} ./hl7v2-json-lake
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-transformer:${{ env.VERSION_TAG }}

      # Build and push Redactor
      - name: Build & Push hl7-redactor
        if: ${{ env.SERVICE_NAME == 'all' || env.SERVICE_NAME == 'redactor' }}
        run: |
          VERSION=$(grep -m1 '<version>' ./hl7v2-redactor/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION ./hl7v2-redactor
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor:$VERSION
