name: Quay Build

on:
  workflow_dispatch:
  push:
   branches:
     - quayioimage
jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      # Build and push Validation
      - name: Build & Push hl7-validation
        env:
          QUAY_REPOSITORY: "us-cdcgov / cdc-dex/hl7-redactor"          
          #VERSION_TAG: "test-2.1.0"
        run: |
          docker build -B -t quay.io/${{ env.QUAY_REPOSITORY }}:${{ env.VERSION_TAG }} ./hl7v2-redactor
          docker push quay.io/${{ env.QUAY_REPOSITORY }}:${{ env.VERSION_TAG }}