name: Quay Build & Publish

on:
  push:
    branches:
      - ci/quay
      - main
  # workflow_dispatch:
  #   inputs:
  #     service_name:
  #       type: choice
  #       description: Service/Image To Build
  #       options:
  #         - validation
  #         - debatcher
  #         - redactor
  #         - lake
  #     version_tag:
  #       description: "Docker Image Version"
  #       required: true
  #       type: string

env:
  QUAY_REPOSITORY: "us-cdcgov/cdc-dex"
  SERVICE_NAME: "all"

jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runner @${{ github.actor }}
        run: |
          echo "--------------------------------------------------"
          echo "Workflow was run by: @${{ github.actor }} \n"
          echo "Service Name: ${{ env.SERVICE_NAME }} \n"
          echo "Version Tag: ${{ env.VERSION_TAG }} \n"
          echo "--------------------------------------------------"

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      # Build and push Validator
      - name: Build & Push hl7-validator
        if: ${{ env.SERVICE_NAME }} == 'all' || ${{ env.SERVICE_NAME }} == 'validator'
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator ./hl7v2-validation
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-validator

      # Build and push Debatcher
      # Test
      - name: Build & Push hl7-debatcher
        if: ${{ env.SERVICE_NAME }} == 'all' || ${{ env.SERVICE_NAME }} == 'debatcher'
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher ./hl7v2-debatcher
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-debatcher

      # Build and push Json-lake
      - name: Build & Push hl7-json-lake
        if: ${{ env.SERVICE_NAME }} == 'all' || ${{ env.SERVICE_NAME }} == 'json-lake'
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7v2-json-lake ./hl7v2-json-lake
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7v2-json-lake

      # Build and push Redactor
      - name: Build & Push hl7-redactor
        if: ${{ env.SERVICE_NAME }} == 'all' || ${{ env.SERVICE_NAME }} == 'redactor'
        run: |
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor ./hl7v2-redactor
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/hl7-redactor
