name: Docker Image Build & Publish

on:
  workflow_dispatch:
    inputs:
      working_path:
        type: string
        description: Service/Image To Build
      # version_tag:
      #   description: "Docker Image Version"
      #   required: true
      #   type: string

# Specify variable SERVICE_NAME to build and publish specific image to Quay
#   Options are all, json-lake, validator, debatcher, redactor
env:
  QUAY_REPOSITORY: "us-cdcgov/cdc-dex"
  
jobs:
  quay_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runner @${{ github.actor }}
        run: |
          echo "--------------------------------------------------"
          echo "Workflow was run by: @${{ github.actor }}"
          echo "Service Name: ${{ inputs.working_path }}
          echo "--------------------------------------------------"

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build and push Container
      - name: Build & Push ${{ inputs.working_path }}
        run: |
          VERSION=$(grep -m1 '<version>' ./${{ inputs.working_path }}/pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          docker build -t quay.io/${{ env.QUAY_REPOSITORY }}/${{ inputs.working_path }}:$VERSION ./${{ inputs.working_path }}
          docker push quay.io/${{ env.QUAY_REPOSITORY }}/${{ inputs.working_path }}:$VERSION
